# Generated by Django 6.0.5 on 2026-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.CharField(choices=[('Django Developer', 'Django Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Python Developer', 'Python Developer')], default='Django Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
